services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  web:
    image: python:3.11-slim
    container_name: python_app
    restart: always
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "pip install Flask Flask-SQLAlchemy pymysql cryptography gunicorn && gunicorn -b 0.0.0.0:8000 --workers 2 --threads 2 --timeout 60 app:app"
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - FLASK_APP=app.py
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge